version: '3.7'
services:
  cron:
    image: pfillion/mobycron:latest
    environment:
      MOBYCRON_DOCKER_MODE: 'swarm'
      MOBYCRON_PARSE_SECOND: 'true'
      TZ: America/New_York
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 30s
      replicas: 1

  busybox:
    image: busybox:latest
    command: echo 'Hello World!!'
    deploy:
      restart_policy:
        condition: none
      replicas: 6
      labels:
        mobycron.schedule: "*/30 * * * * *"
        mobycron.action: "update"