version: '3.6'
services:
  cron:
    image: pfillion/mobycron:latest
    environment:
      MOBYCRON_DOCKER_MODE: 'true'
      MOBYCRON_PARSE_SECOND: 'true'
      CRON_TZ: America/New_York
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      mode: global

  busybox:
    image: busybox:latest
    command: echo 'Hello World!!'
    labels: 
      mobycron.schedule: "*/30 * * * * *"
      mobycron.action: "start"
    deploy:
      replicas: 6
      restart_policy:
        condition: none