version: '3.6'
services:
  cron:
    image: pfillion/mobycron:latest
    environment:
      - TZ=America/New_York
      - NAME=World!!!
      - REPO__FILE=/run/secrets/restic-repo
    configs:
      - source: mobycron-config
        target: /configs/config.json
    secrets:
      - source: restic-passwd
        target: /configs/passwd
      - restic-repo

configs:
  mobycron-config:
    external: true

secrets:
  restic-repo:
    external: true
  restic-passwd:
    external: true