// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/spacekitty/ownCloud/Document/dev/go/src/github.com/pfillion/mobycron/cron/cron.go

// Package cron is a generated GoMock package.
package cron

import (
	gomock "github.com/golang/mock/gomock"
	cron "github.com/robfig/cron"
	reflect "reflect"
)

// MockRunner is a mock of Runner interface
type MockRunner struct {
	ctrl     *gomock.Controller
	recorder *MockRunnerMockRecorder
}

// MockRunnerMockRecorder is the mock recorder for MockRunner
type MockRunnerMockRecorder struct {
	mock *MockRunner
}

// NewMockRunner creates a new mock instance
func NewMockRunner(ctrl *gomock.Controller) *MockRunner {
	mock := &MockRunner{ctrl: ctrl}
	mock.recorder = &MockRunnerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockRunner) EXPECT() *MockRunnerMockRecorder {
	return m.recorder
}

// AddJob mocks base method
func (m *MockRunner) AddJob(spec string, cmd cron.Job) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddJob", spec, cmd)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddJob indicates an expected call of AddJob
func (mr *MockRunnerMockRecorder) AddJob(spec, cmd interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddJob", reflect.TypeOf((*MockRunner)(nil).AddJob), spec, cmd)
}

// Start mocks base method
func (m *MockRunner) Start() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Start")
}

// Start indicates an expected call of Start
func (mr *MockRunnerMockRecorder) Start() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockRunner)(nil).Start))
}

// Stop mocks base method
func (m *MockRunner) Stop() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Stop")
}

// Stop indicates an expected call of Stop
func (mr *MockRunnerMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockRunner)(nil).Stop))
}

// MockJobSynchroniser is a mock of JobSynchroniser interface
type MockJobSynchroniser struct {
	ctrl     *gomock.Controller
	recorder *MockJobSynchroniserMockRecorder
}

// MockJobSynchroniserMockRecorder is the mock recorder for MockJobSynchroniser
type MockJobSynchroniserMockRecorder struct {
	mock *MockJobSynchroniser
}

// NewMockJobSynchroniser creates a new mock instance
func NewMockJobSynchroniser(ctrl *gomock.Controller) *MockJobSynchroniser {
	mock := &MockJobSynchroniser{ctrl: ctrl}
	mock.recorder = &MockJobSynchroniserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockJobSynchroniser) EXPECT() *MockJobSynchroniserMockRecorder {
	return m.recorder
}

// Add mocks base method
func (m *MockJobSynchroniser) Add(delta int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Add", delta)
}

// Add indicates an expected call of Add
func (mr *MockJobSynchroniserMockRecorder) Add(delta interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockJobSynchroniser)(nil).Add), delta)
}

// Done mocks base method
func (m *MockJobSynchroniser) Done() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Done")
}

// Done indicates an expected call of Done
func (mr *MockJobSynchroniserMockRecorder) Done() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Done", reflect.TypeOf((*MockJobSynchroniser)(nil).Done))
}

// Wait mocks base method
func (m *MockJobSynchroniser) Wait() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Wait")
}

// Wait indicates an expected call of Wait
func (mr *MockJobSynchroniserMockRecorder) Wait() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Wait", reflect.TypeOf((*MockJobSynchroniser)(nil).Wait))
}
